/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Arithmetic;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test
    public void TestMultiplyUsingExample1() {
        int expected = 6;
        int actual = Library.Multiply(2, 3);
        assertEquals(expected, actual);
    }

    @Test
    public void TestMultiplyUsingExample2() {
        int expected = 20;
        int actual = Library.Multiply(4, 5);
        assertEquals(expected, actual);
    }
}
